---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-ecommerce-app-deployment
spec:
  selector:
    matchLabels:
      app: java-ecommerce-app
  replicas: 2
  template:
    metadata:
      labels:
        app: java-ecommerce-app
    spec:
      containers:
        - name: java-ecommerce-app
          image: jayeshrajput/java-ecommerce-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: java-ecommerce-app-svc
spec:
  selector:
    app: java-ecommerce-app
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: NodePort
